### GET request with a header
GET {{url}}/product/queryAllProduct
Accept: application/json


### GET request with a header
GET {{url}}/product/findByProductId/1

### GET request with a header
GET {{url}}/product/findByProductId/0

### GET request with a header
GET {{url}}/stock/stock/findStockByProductId/1

### Send POST request with json body
POST {{url}}/stock/stock/deductionStock?productId=1&count=1
#Content-Type: application/x-www-form-urlencoded
#
#{
#  "productId": 1,
#  "count": 1
#}

### GET request with a header

GET {{url}}/order/queryAllOrder

### Send POST request with json body
POST {{url}}/order/submitOrder?productId=2&orderProductName="美女"&orderPrice=999.0&count=1
#Content-Type: application/x-www-form-urlencoded

#productId=2&orderProductName="美女"&orderPrice=999.0&count=1

#{
#  "productId": 2,
#  "orderProductName": "美女" ,
#  "orderPrice": 999.0,
#  "count": 1
#}
