---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway 
  namespace: ms 
spec:
  rules:
    - host: gateway.ctnrs.com 
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: gateway
            servicePort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ms
spec:
  ports:
  - port: 9999 
    name: gateway
  selector:
    project: ms
    app: gateway
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: gateway
  namespace: ms 
spec:
  replicas: 2
  selector:
    matchLabels:
      project: ms
      app: gateway
  template:
    metadata:
      labels:
        project: ms 
        app: gateway
    spec:
      #构建初始化镜像(通过初始化镜像的方式集成SkyWalking Agent)
      initContainers:
        - image: harbor.husx.top/microservice/skywalking-agent:8.3.0-2
          name: sw-agent-sidecar
          imagePullPolicy: IfNotPresent
          command:
            - 'sh'
            - '-c'
            - 'set -ex && mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent  '
          volumeMounts:
            - mountPath: /skywalking/agent
              name: sw-agent
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - name: gateway
        image: harbor.husx.top/microservice/gateway-service:dev-1.0.3
        imagePullPolicy: Always
        ports:
          - protocol: TCP
            containerPort: 9999 
        env:
          - name: SW_AGENT_NAME
            value: gateway
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            # FQDN: servicename.namespacename.svc.cluster.local
            value: skywalking-oap.skywalking:11800
            #这里通过JAVA_TOOL_OPTIONS，而不是JAVA_OPTS可以实现不通过将agent命令加入到java应用jvm参数而实现agent的集成
          - name: JAVA_TOOL_OPTIONS
            value:
              -Dskywalking.agent.service_name=gateway
              -javaagent:/usr/skywalking/agent/skywalking-agent.jar
              -Dskywalking.collector.backend_service=skywalking-oap.skywalking:11800

          - name: JAVA_OPTS
            value: "-Xmx512m"
          - name: APP_OPTS
            value: "--spring.profiles.active=fat"
        volumeMounts:
          - mountPath: /usr/skywalking/agent
            name: sw-agent
        resources:
          requests:
            cpu: 0.1
            memory: 512Mi
          limits:
            cpu: 0.5
            memory: 800Mi
        # readinessProbe:
        #   tcpSocket:
        #     port: 9999
        #   initialDelaySeconds: 120
        #   periodSeconds: 20
        livenessProbe:
          tcpSocket:
            port: 9999
          initialDelaySeconds: 120
          periodSeconds: 10
      volumes:
        - name: sw-agent
          emptyDir: { }
