apiVersion: apps/v1
kind: Deployment 
metadata:
  name: order
  namespace: ms 
spec:
  replicas: 2
  selector:
    matchLabels:
      project: ms
      app: order
  template:
    metadata:
      labels:
        project: ms 
        app: order
    spec:
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - name: order
        image: harbor.husx.top/microservice/order-service:dev-1.0.3
        imagePullPolicy: Always
        ports:
          - protocol: TCP
            containerPort: 8020 
        env:
          - name: JAVA_OPTS
            value: "-Xmx256m"
          - name: APP_OPTS
            value: "--spring.profiles.active=fat"
        resources:
          requests:
            cpu: 0.1
            memory: 256Mi
          limits:
            cpu: 0.3
            memory: 512Mi
        # readinessProbe:
        #   tcpSocket:
        #     port: 8020
        #   initialDelaySeconds: 120
        #   periodSeconds: 20
        livenessProbe:
          tcpSocket:
            port: 8020
          initialDelaySeconds: 60
          periodSeconds: 10
