apiVersion: apps/v1
kind: Deployment 
metadata:
  name: product
  namespace: ms 
spec:
  replicas: 2
  selector:
    matchLabels:
      project: ms
      app: product
  template:
    metadata:
      labels:
        project: ms 
        app: product
    spec:
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - name: product
        image: harbor.husx.top/microservice/product-service:dev-1.0
        imagePullPolicy: Always
        ports:
          - protocol: TCP
            containerPort: 8010 
        env:
          - name: JAVA_OPTS
            value: "-Xmx256m"
        resources:
          requests:
            cpu: 0.1
            memory: 256Mi
          limits:
            cpu: 0.3
            memory: 512Mi
        readinessProbe:
          tcpSocket:
            port: 8010
          initialDelaySeconds: 120
          periodSeconds: 20
        livenessProbe:
          tcpSocket:
            port: 8010
          initialDelaySeconds: 120
          periodSeconds: 20
