---
apiVersion: v1
kind: Service
metadata:
  name: stock
  namespace: ms
spec:
  ports:
  - port: 9999 
    name: stock
  selector:
    project: ms
    app: stock
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: stock
  namespace: ms 
spec:
  replicas: 2
  selector:
    matchLabels:
      project: ms
      app: stock
  template:
    metadata:
      labels:
        project: ms 
        app: stock
    spec:
      #构建初始化镜像(通过初始化镜像的方式集成SkyWalking Agent)
      initContainers:
        - image: harbor.husx.top/microservice/skywalking-agent:8.3.0-2
          name: sw-agent-sidecar
          imagePullPolicy: IfNotPresent
          command:
            - 'sh'
            - '-c'
            - 'set -ex && mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent  '

          #        command: [ "sh" ]
  #        args:
  #          [
  #              "-c",
  #              "set -ex && mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent"
  #          ]
          volumeMounts:
            - mountPath: /skywalking/agent
              name: sw-agent
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - name: stock
        image: harbor.husx.top/microservice/stock-service:dev-1.0.4
        imagePullPolicy: Always
        ports:
          - protocol: TCP
            containerPort: 8030
        env:
          - name: SW_AGENT_NAME
            value: stock
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            # FQDN: servicename.namespacename.svc.cluster.local
            value: skywalking-oap.skywalking:11800
            #这里通过JAVA_TOOL_OPTIONS，而不是JAVA_OPTS可以实现不通过将agent命令加入到java应用jvm参数而实现agent的集成
          - name: JAVA_TOOL_OPTIONS
            value: -javaagent:/usr/skywalking/agent/skywalking-agent.jar -Dskywalking.collector.backend_service=skywalking-oap.skywalking:11800 -Dskywalking.agent.service_name=stock

          - name: JAVA_OPTS
            value: "-Xmx512m "
#          - name:
          - name: APP_OPTS
            value: "--spring.profiles.active=fat"
        volumeMounts:
          - mountPath: /usr/skywalking/agent
            name: sw-agent
        resources:
          requests:
            cpu: 0.1
            memory: 256Mi
          limits:
            cpu: 0.5
            memory: 800Mi
        # readinessProbe:
        #   tcpSocket:
        #     port: 8030
        #   initialDelaySeconds: 120
        #   periodSeconds: 20
        livenessProbe:
          tcpSocket:
            port: 8030
          initialDelaySeconds: 120
          periodSeconds: 10
      volumes:
        - name: sw-agent
          emptyDir: { }
